name: Pull Request verification

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: './src/WebBlog/appsettings.json, ./src/WebBlog.Test/appsettings.json'
      env:
        DEVTOAPI: ${{ secrets.DEVTOAPI }}
        DEVTOURL: ${{ secrets.DEVTOURL }}
    - name: Build
      run: dotnet build -c Release --no-cache ./src/WebBlog.Test/WebBlog.Test.csproj
        
    - name: Run the Unit and Integration Tests
      run: dotnet test -c Release --no-build ./src/WebBlog.Test/WebBlog.Test.csproj
      
    - name: Run Code Coverage
      run: dotnet test -c Release --no-build /p:CollectCoverage=true /p:CoverletOutput="../" /p:ExcludeByFile=\"**/Migrations/**/*%2c**/Models/**/*%2c**/Views/**/*\" /p:MergeWith="../coverage.json" /maxcpucount:1 /p:CoverletOutputFormat=\"json,opencover\" ./src/WebBlog.Test/WebBlog.Test.csproj
    
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./src/coverage.opencover.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
